name: Code Cleanliness Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Run Check Code Cleanliness with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: quay.io/eclipse-cdt/cdt-infra-plus-eclipse-install-github@sha256:6188eac52d93bcd532de6e6eb42f1065c5ff18c0bccb6461581f45e4a158d776
          options: -v ${{ github.workspace }}:/work --user 1001:127
          run: |
            set -x
            ls -la /
            ls -la /work
            whoami
            cd /work
            xvfb-run -a ./releng/scripts/check_code_cleanliness_only.sh
            ./releng/scripts/check_bundle_versions.sh
            ./releng/scripts/check_bundle_versions_report.sh
      - name: Upload Logs
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: Code Cleanliness Detailed Logs
          path: "*.log"
