name: Code Cleanliness Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Run Check Code Cleanliness with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: quay.io/eclipse-cdt/cdt-infra-plus-eclipse-install@sha256:53be2931e1ce9694033e46784d9b1b841a4399b16f3b0c00bc5f07178d1cb125
          options: -v ${{ github.workspace }}:/work --user 1001:127
          run: |
            set -x
            ls -la /
            ls -la /work
            whoami
            cd /work
            ./releng/scripts/check_code_cleanliness_only.sh
            ./releng/scripts/check_bundle_versions.sh
            ./releng/scripts/check_bundle_versions_report.sh
      - name: Upload Logs
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: Code Cleanliness Detailed Logs
          path: "*.log"
